### ISSUE TITLE
Host using Github + Netlify

### ISSUE THREAD

**Issue by IsmailM** [bionode/bionode.github.io#12]
I would suggest that we use [Netlify](https://www.netlify.com) to host the Bionode website:

Pros:

- one click (Let's Encrypt) SSL certificate (not currently possible on GitHub with a custom domain - a requested feature from over three years ago)
- CDN - so faster
- uses HTTP2
- Continuous Deployment with Github - so rebuilds with each Git push
- FREE!!!

CONS:
- Only @bmpvieira can access Netlify admin panel - No team support on the free package (though not sure what they mean on their website by unlimited collaborators on the [open source page](https://www.netlify.com/open-source/)...

Tutorial: https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/

Note - we might not even need Travis anymore to run the build command - it's possible to do this with netlify.

This is what happens when we run the website through the netlify site tester:

![testmysite_io___netlify_speedtest](https://user-images.githubusercontent.com/5578375/30325417-910e4204-97bc-11e7-9e07-1c62c2ed7290.png)

**Comment by thejmazz** [comment]
This looks like it might be better than [surge](https://surge.sh/) due to SSL (free surge only has "basic SSL" and no http -> https 301s). I'm happy with any website hosting option as long as it does not dramatically change code to be vendor specific.

**Comment by bmpvieira** [comment]
Thank @IsmailM for finding this! I've added this repo to Netlify and made you both admins. @IsmailM can you check why it's failing? Some issue with the Streaming scripts. Let me know if you need more permissions or me to click somewhere. Cheers.

**Comment by IsmailM** [comment]
Fixed it by changing branch to master (our building process isn't that simple ;) )...

Also: 

- we have cron jobs on Travis (to rebuild the list of users - see [here](https://github.com/bionode/bionode.github.io/blob/dev/deploy.sh#L8-L15)) - don't think cron jobs are possible via netlify...

- also the deploy script requires the latest version of jq (we had to manually install it with travis as default version was too old) - not sure how easy it is to do this on netlify...

So, we should continue to build via travis and then simply host the master branch... Netlify will automatically update on each git push - so should update after each travis cron job...


https://bionode.netlify.com/

**Comment by IsmailM** [comment]
@bmpvieira - can you set up the DNS for bionode.io

https://www.netlify.com/blog/2016/03/14/setting-up-your-custom-domain/

**Comment by IsmailM** [comment]
Now using Netlify: https://www.bionode.io/

Will add a http:// to https:// redirection once #13 is merged...
